<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BDC7-L-1Z7XLV1" name="Test" tests="2" failures="0" timestamp="23 Dec 2016 11:48:58 GMT" time="0.868" errors="0">
  <testcase name="@BeforeSuite beforeSuite" time="0.0" classname="mwo.tests.LoginTests">
    <failure type="java.lang.ExceptionInInitializerError">
      <![CDATA[java.lang.ExceptionInInitializerError
	at com.appium.base.AppiumSingleTest.findCustomNode(Unknown Source)
	at com.appium.base.AppiumSingleTest.startAppiumServer(Unknown Source)
	at com.appium.testng.TestBaseStandalone.beforeSuite(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.appium.base.Utils.loadProperties(Unknown Source)
	at com.appium.base.Utils.<clinit>(Unknown Source)
	... 20 more
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeSuite beforeSuite -->
  <testcase name="@BeforeMethod beforeMethod" time="0.0" classname="mwo.tests.LoginTests">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at java.util.Properties$LineReader.readLine(Properties.java:434)
	at java.util.Properties.load0(Properties.java:353)
	at java.util.Properties.load(Properties.java:341)
	at com.report.factory.ExtentTestManager.startTest(ExtentTestManager.java:45)
	at com.appium.testng.TestBaseStandalone.beforeMethod(Unknown Source)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod beforeMethod -->
  <testcase name="@AfterMethod afterMethod" time="0.0" classname="mwo.tests.LoginTests">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.appium.testng.TestBaseStandalone.captureFinalScreenshot(Unknown Source)
	at com.appium.testng.TestBaseStandalone.afterMethod(Unknown Source)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod afterMethod -->
  <testcase name="@BeforeMethod beforeMethod" time="0.0" classname="mwo.tests.LoginTests">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at java.util.Properties$LineReader.readLine(Properties.java:434)
	at java.util.Properties.load0(Properties.java:353)
	at java.util.Properties.load(Properties.java:341)
	at com.report.factory.ExtentTestManager.startTest(ExtentTestManager.java:45)
	at com.appium.testng.TestBaseStandalone.beforeMethod(Unknown Source)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod beforeMethod -->
  <testcase name="@AfterMethod afterMethod" time="0.0" classname="mwo.tests.LoginTests">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.appium.testng.TestBaseStandalone.captureFinalScreenshot(Unknown Source)
	at com.appium.testng.TestBaseStandalone.afterMethod(Unknown Source)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod afterMethod -->
  <testcase name="testInValidLogin" time="0.0" classname="mwo.tests.LoginTests">
    <skipped/>
  </testcase> <!-- testInValidLogin -->
  <testcase name="testValidLogin" time="0.0" classname="mwo.tests.LoginTests">
    <skipped/>
  </testcase> <!-- testValidLogin -->
</testsuite> <!-- Test -->
